name: 'Build and Deploy Site'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: | 
          cd app
          npm ci
          CI=false npm run deploy